### ISSUE TITLE
v1.4 High-level Roadmap

### ISSUE THREAD

**Issue by thebracket** [LibreQoE/LibreQoS#181]
*This is a flexible item, designed to outline some of what we're working on for the next release. Please feel free to edit, rearrange, etc.*

- [x] Move XDP code into a new project.
- [x] Wrap XDP in a daemon that can be controlled like a regular `systemd` daemon, allowing start/stop as normal.
- [x] Add `/etc/lqos` to indicate where LibreQoS is installed and which instance is active.
- [x] Create a "local control bus" to provide easy control of `lqosd` from user-space applications.
- [x] Create a Python library for controlling the system via the `lqosd` bus.
- [x] Extend XDP system to track known and unknown users and their recent (5m) throughput and RTT.
- [x] Create a local web GUI that can display a throughput, RTT, CPU and RAM utilization dashboard.
- [x] Support local configuration from the local web GUI
- [x] "On a stick" mode, allowing LibreQoS to run on a single interface with VLANs for "in" and "out"
- [x] 2-interface "no bridge" mode, using XDP redirect to bypass the need to create a Linux bridge.
- [x] 1-interface "no bridge" mode, using XDP/TC redirect to forward between VLANs without a Linux bridge.
- [x] Shape 25 gbit/s of traffic without melting a 16-core system.
- [x] Monitor queues and topology and obtain statistics from within `lqosd`.
- [x] Maintain a ring-buffer of queue statistics for local GUI browsing.
- [x] Support reading data from PPPoE encapsulated packets.

You can access the ongoing local GUI work [here](http://payne.taht.net:9123/)

## Punted:

- [ ] Modular statistics export, providing configurable export to Influx, Zabbix and similar.
- [ ] Long-term statistics GUI.
- [ ] Fixes for >8 deep HTB tree hierarchy.
- [ ] Support reading data from MPLS packets (1 and 2 layers of tags)
